
# Define target output
target: dcp

# Define target part
export PRJ_PART = XCKU040-FFVA1156-2-E

export PROJECT = SaltUltraScaleTxOnly
export TOP_DIR = $(abspath $(PWD)/../../../../../..)
export MODULES = $(abspath ../../../../..)

# Use top level makefile
include $(MODULES)/ruckus/system_vivado.mk
