######################################
# BITSTREAM: .bit file Configuration #
######################################

set_property BITSTREAM.CONFIG.CONFIGRATE 9 [current_design]   
set_property CFGBVS VCCO         [current_design]
set_property CONFIG_VOLTAGE 3.3  [current_design] 

##############################
# StdLib: Custom Constraints #
##############################

set_property ASYNC_REG TRUE [get_cells -hierarchical *crossDomainSyncReg_reg*]

#####################
# DDR SO-DIMM Ports #
#####################

set_property PACKAGE_PIN      AJ21        [get_ports {ddrClkP}] 
set_property PACKAGE_PIN      AK21        [get_ports {ddrClkN}] 
set_property IOSTANDARD       DIFF_HSTL_I [get_ports {ddrClkP ddrClkN}]
set_property IBUF_LOW_PWR     FALSE       [get_ports {ddrClkP ddrClkN}]
set_property PULLTYPE         KEEPER      [get_ports {ddrClkP ddrClkN}]
create_clock -name ddrClkP -period 5.0    [get_ports ddrClkP]

set_property CLOCK_DEDICATED_ROUTE FALSE    [get_nets {U_DdrMem/refClock}]
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets {U_DdrMem/refClkBufg}]

set_property PACKAGE_PIN AL27 [get_ports {ddrDqsP[0]}] 
set_property PACKAGE_PIN AL28 [get_ports {ddrDqsN[0]}] 
set_property PACKAGE_PIN AN29 [get_ports {ddrDqsP[1]}] 
set_property PACKAGE_PIN AP30 [get_ports {ddrDqsN[1]}] 
set_property PACKAGE_PIN AH33 [get_ports {ddrDqsP[2]}] 
set_property PACKAGE_PIN AJ33 [get_ports {ddrDqsN[2]}] 
set_property PACKAGE_PIN AN34 [get_ports {ddrDqsP[3]}] 
set_property PACKAGE_PIN AP34 [get_ports {ddrDqsN[3]}] 
set_property PACKAGE_PIN AN18 [get_ports {ddrDqsP[4]}] 
set_property PACKAGE_PIN AN17 [get_ports {ddrDqsN[4]}] 
set_property PACKAGE_PIN AL18 [get_ports {ddrDqsP[5]}] 
set_property PACKAGE_PIN AL17 [get_ports {ddrDqsN[5]}] 
set_property PACKAGE_PIN AJ15 [get_ports {ddrDqsP[6]}] 
set_property PACKAGE_PIN AJ14 [get_ports {ddrDqsN[6]}] 
set_property PACKAGE_PIN AE16 [get_ports {ddrDqsP[7]}] 
set_property PACKAGE_PIN AE15 [get_ports {ddrDqsN[7]}] 
set_property IOSTANDARD DIFF_SSTL15_DCI   [get_ports {ddrDqsP[*] ddrDqsN[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40  [get_ports {ddrDqsP[*] ddrDqsN[*]}]
set_property SLEW          FAST           [get_ports {ddrDqsP[*] ddrDqsN[*]}]
set_property IBUF_LOW_PWR  FALSE          [get_ports {ddrDqsP[*] ddrDqsN[*]}]
set_property ODT           RTT_40         [get_ports {ddrDqsP[*] ddrDqsN[*]}]

set_property PACKAGE_PIN AH26 [get_ports {ddrDm[0]}] 
set_property PACKAGE_PIN AN26 [get_ports {ddrDm[1]}] 
set_property PACKAGE_PIN AJ29 [get_ports {ddrDm[2]}] 
set_property PACKAGE_PIN AL32 [get_ports {ddrDm[3]}] 
set_property PACKAGE_PIN AN14 [get_ports {ddrDm[4]}] 
set_property PACKAGE_PIN AL14 [get_ports {ddrDm[5]}] 
set_property PACKAGE_PIN AH18 [get_ports {ddrDm[6]}] 
set_property PACKAGE_PIN AD19 [get_ports {ddrDm[7]}] 
set_property IOSTANDARD SSTL15_DCI        [get_ports {ddrDm[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40  [get_ports {ddrDm[*]}]
set_property SLEW FAST                    [get_ports {ddrDm[*]}]

set_property PACKAGE_PIN AM26 [get_ports {ddrDq[0]}] 
set_property PACKAGE_PIN AM27 [get_ports {ddrDq[1]}] 
set_property PACKAGE_PIN AK26 [get_ports {ddrDq[2]}] 
set_property PACKAGE_PIN AK27 [get_ports {ddrDq[3]}] 
set_property PACKAGE_PIN AH27 [get_ports {ddrDq[4]}] 
set_property PACKAGE_PIN AH28 [get_ports {ddrDq[5]}] 
set_property PACKAGE_PIN AJ28 [get_ports {ddrDq[6]}] 
set_property PACKAGE_PIN AK28 [get_ports {ddrDq[7]}] 
set_property PACKAGE_PIN AP28 [get_ports {ddrDq[8]}] 
set_property PACKAGE_PIN AP29 [get_ports {ddrDq[9]}] 
set_property PACKAGE_PIN AN27 [get_ports {ddrDq[10]}] 
set_property PACKAGE_PIN AN28 [get_ports {ddrDq[11]}] 
set_property PACKAGE_PIN AL29 [get_ports {ddrDq[12]}] 
set_property PACKAGE_PIN AM29 [get_ports {ddrDq[13]}] 
set_property PACKAGE_PIN AL30 [get_ports {ddrDq[14]}] 
set_property PACKAGE_PIN AM30 [get_ports {ddrDq[15]}] 
set_property PACKAGE_PIN AK31 [get_ports {ddrDq[16]}] 
set_property PACKAGE_PIN AK32 [get_ports {ddrDq[17]}] 
set_property PACKAGE_PIN AJ30 [get_ports {ddrDq[18]}] 
set_property PACKAGE_PIN AJ31 [get_ports {ddrDq[19]}] 
set_property PACKAGE_PIN AH31 [get_ports {ddrDq[20]}] 
set_property PACKAGE_PIN AH32 [get_ports {ddrDq[21]}] 
set_property PACKAGE_PIN AH34 [get_ports {ddrDq[22]}] 
set_property PACKAGE_PIN AJ34 [get_ports {ddrDq[23]}] 
set_property PACKAGE_PIN AN33 [get_ports {ddrDq[24]}] 
set_property PACKAGE_PIN AP33 [get_ports {ddrDq[25]}] 
set_property PACKAGE_PIN AN31 [get_ports {ddrDq[26]}] 
set_property PACKAGE_PIN AP31 [get_ports {ddrDq[27]}] 
set_property PACKAGE_PIN AM32 [get_ports {ddrDq[28]}] 
set_property PACKAGE_PIN AN32 [get_ports {ddrDq[29]}] 
set_property PACKAGE_PIN AL34 [get_ports {ddrDq[30]}] 
set_property PACKAGE_PIN AM34 [get_ports {ddrDq[31]}] 
set_property PACKAGE_PIN AN19 [get_ports {ddrDq[32]}] 
set_property PACKAGE_PIN AP18 [get_ports {ddrDq[33]}] 
set_property PACKAGE_PIN AM17 [get_ports {ddrDq[34]}] 
set_property PACKAGE_PIN AN16 [get_ports {ddrDq[35]}] 
set_property PACKAGE_PIN AM16 [get_ports {ddrDq[36]}] 
set_property PACKAGE_PIN AM15 [get_ports {ddrDq[37]}] 
set_property PACKAGE_PIN AP16 [get_ports {ddrDq[38]}] 
set_property PACKAGE_PIN AP15 [get_ports {ddrDq[39]}] 
set_property PACKAGE_PIN AL19 [get_ports {ddrDq[40]}] 
set_property PACKAGE_PIN AM19 [get_ports {ddrDq[41]}] 
set_property PACKAGE_PIN AK15 [get_ports {ddrDq[42]}] 
set_property PACKAGE_PIN AL15 [get_ports {ddrDq[43]}] 
set_property PACKAGE_PIN AJ18 [get_ports {ddrDq[44]}] 
set_property PACKAGE_PIN AK18 [get_ports {ddrDq[45]}] 
set_property PACKAGE_PIN AK17 [get_ports {ddrDq[46]}] 
set_property PACKAGE_PIN AK16 [get_ports {ddrDq[47]}] 
set_property PACKAGE_PIN AH16 [get_ports {ddrDq[48]}] 
set_property PACKAGE_PIN AJ16 [get_ports {ddrDq[49]}] 
set_property PACKAGE_PIN AG17 [get_ports {ddrDq[50]}] 
set_property PACKAGE_PIN AG16 [get_ports {ddrDq[51]}] 
set_property PACKAGE_PIN AG19 [get_ports {ddrDq[52]}] 
set_property PACKAGE_PIN AH19 [get_ports {ddrDq[53]}] 
set_property PACKAGE_PIN AG15 [get_ports {ddrDq[54]}] 
set_property PACKAGE_PIN AG14 [get_ports {ddrDq[55]}] 
set_property PACKAGE_PIN AF15 [get_ports {ddrDq[56]}] 
set_property PACKAGE_PIN AF14 [get_ports {ddrDq[57]}] 
set_property PACKAGE_PIN AE18 [get_ports {ddrDq[58]}] 
set_property PACKAGE_PIN AF18 [get_ports {ddrDq[59]}] 
set_property PACKAGE_PIN AE17 [get_ports {ddrDq[60]}] 
set_property PACKAGE_PIN AF17 [get_ports {ddrDq[61]}] 
set_property PACKAGE_PIN AD16 [get_ports {ddrDq[62]}] 
set_property PACKAGE_PIN AD15 [get_ports {ddrDq[63]}] 
set_property IOSTANDARD SSTL15_DCI        [get_ports {ddrDq[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40  [get_ports {ddrDq[*]}]
set_property SLEW          FAST           [get_ports {ddrDq[*]}]
set_property IBUF_LOW_PWR  FALSE          [get_ports {ddrDq[*]}]
set_property ODT           RTT_40         [get_ports {ddrDq[*]}]

set_property PACKAGE_PIN AD21 [get_ports {ddrA[0]}] 
set_property PACKAGE_PIN AE21 [get_ports {ddrA[1]}] 
set_property PACKAGE_PIN AF20 [get_ports {ddrA[2]}] 
set_property PACKAGE_PIN AG20 [get_ports {ddrA[3]}] 
set_property PACKAGE_PIN AD20 [get_ports {ddrA[4]}] 
set_property PACKAGE_PIN AE20 [get_ports {ddrA[5]}] 
set_property PACKAGE_PIN AE22 [get_ports {ddrA[6]}] 
set_property PACKAGE_PIN AE23 [get_ports {ddrA[7]}] 
set_property PACKAGE_PIN AF22 [get_ports {ddrA[8]}] 
set_property PACKAGE_PIN AG22 [get_ports {ddrA[9]}] 
set_property PACKAGE_PIN AE25 [get_ports {ddrA[10]}] 
set_property PACKAGE_PIN AE26 [get_ports {ddrA[11]}] 
set_property PACKAGE_PIN AF23 [get_ports {ddrA[12]}] 
set_property PACKAGE_PIN AF24 [get_ports {ddrA[13]}] 
set_property PACKAGE_PIN AG24 [get_ports {ddrA[14]}] 
set_property PACKAGE_PIN AG25 [get_ports {ddrA[15]}]
set_property IOSTANDARD SSTL15_DCI        [get_ports {ddrA[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40  [get_ports {ddrA[*]}]
set_property SLEW FAST                    [get_ports {ddrA[*]}]

set_property PACKAGE_PIN AH24 [get_ports {ddrBa[0]}] 
set_property PACKAGE_PIN AJ25 [get_ports {ddrBa[1]}] 
set_property PACKAGE_PIN AJ23 [get_ports {ddrBa[2]}] 
set_property IOSTANDARD SSTL15_DCI        [get_ports {ddrBa[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40  [get_ports {ddrBa[*]}]
set_property SLEW FAST                    [get_ports {ddrBa[*]}]

set_property PACKAGE_PIN AJ24 [get_ports {ddrCsL[0]}] 
set_property PACKAGE_PIN AM24 [get_ports {ddrCsL[1]}] 
set_property IOSTANDARD SSTL15_DCI        [get_ports {ddrCsL[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40  [get_ports {ddrCsL[*]}]
set_property SLEW FAST                    [get_ports {ddrCsL[*]}]

set_property PACKAGE_PIN AH23 [get_ports {ddrOdt[0]}] 
set_property PACKAGE_PIN AN24 [get_ports {ddrOdt[1]}] 
set_property IOSTANDARD SSTL15_DCI        [get_ports {ddrOdt[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40  [get_ports {ddrOdt[*]}]
set_property SLEW FAST                    [get_ports {ddrOdt[*]}]

set_property PACKAGE_PIN AH22 [get_ports {ddrCke[0]}] 
set_property PACKAGE_PIN AL25 [get_ports {ddrCke[1]}] 
set_property IOSTANDARD SSTL15_DCI        [get_ports {ddrCke[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40  [get_ports {ddrCke[*]}]
set_property SLEW FAST                    [get_ports {ddrCke[*]}]

set_property PACKAGE_PIN AG21 [get_ports {ddrCkP[0]}] 
set_property PACKAGE_PIN AH21 [get_ports {ddrCkN[0]}] 
set_property PACKAGE_PIN AL22 [get_ports {ddrCkP[1]}] 
set_property PACKAGE_PIN AL23 [get_ports {ddrCkN[1]}] 
set_property IOSTANDARD DIFF_SSTL15_DCI   [get_ports {ddrCkP[*] ddrCkN[*]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40  [get_ports {ddrCkP[*] ddrCkN[*]}]
set_property SLEW FAST                    [get_ports {ddrCkP[*] ddrCkN[*]}]

set_property -dict { PACKAGE_PIN AL20 IOSTANDARD SSTL15_DCI OUTPUT_IMPEDANCE RDRV_40_40 SLEW FAST } [get_ports {ddrWeL}] 
set_property -dict { PACKAGE_PIN AK22 IOSTANDARD SSTL15_DCI OUTPUT_IMPEDANCE RDRV_40_40 SLEW FAST } [get_ports {ddrRasL}] 
set_property -dict { PACKAGE_PIN AK23 IOSTANDARD SSTL15_DCI OUTPUT_IMPEDANCE RDRV_40_40 SLEW FAST } [get_ports {ddrCasL}] 
set_property -dict { PACKAGE_PIN AF25 IOSTANDARD SSTL15     OUTPUT_IMPEDANCE RDRV_48_48 SLEW SLOW } [get_ports {ddrRstL}] 

set_property -dict { PACKAGE_PIN AP11 IOSTANDARD LVCMOS33 PULLUP true } [get_ports {ddrScl}] 
set_property -dict { PACKAGE_PIN AP10 IOSTANDARD LVCMOS33 PULLUP true } [get_ports {ddrSda}] 
set_property -dict { PACKAGE_PIN K26  IOSTANDARD LVCMOS33 PULLUP true } [get_ports {ddrPwrEnL}] 
set_property -dict { PACKAGE_PIN J24  IOSTANDARD LVCMOS33 PULLUP true } [get_ports {ddrPg}] 
set_property -dict { PACKAGE_PIN J25  IOSTANDARD LVCMOS33 PULLUP true } [get_ports {ddrAlertL}] 
