-------------------------------------------------------------------------------
-- This file is part of 'SLAC Firmware Standard Library'.
-- It is subject to the license terms in the LICENSE.txt file found in the
-- top-level directory of this distribution and at:
--    https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html.
-- No part of 'SLAC Firmware Standard Library', including this file,
-- may be copied, modified, propagated, or distributed except according to
-- the terms contained in the LICENSE.txt file.
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
-- Generated by bsc2vhdl 0.1.0 from mkAxisTransportLayer.v.
-- Do not hand-edit: re-run the transpiler to regenerate this file.
-------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library surf;
use surf.StdRtlPkg.all;

entity mkAxiSTransportLayer is
   port (
      CLK                        : in  sl;
      RST_N                      : in  sl;
      s_work_req_valid           : in  sl;
      s_work_req_id              : in  slv(63 downto 0);
      s_work_req_op_code         : in  slv(3 downto 0);
      s_work_req_flags           : in  slv(4 downto 0);
      s_work_req_raddr           : in  slv(63 downto 0);
      s_work_req_rkey            : in  slv(31 downto 0);
      s_work_req_len             : in  slv(31 downto 0);
      s_work_req_laddr           : in  slv(63 downto 0);
      s_work_req_lkey            : in  slv(31 downto 0);
      s_work_req_sqpn            : in  slv(23 downto 0);
      s_work_req_solicited       : in  sl;
      s_work_req_comp            : in  slv(64 downto 0);
      s_work_req_swap            : in  slv(64 downto 0);
      s_work_req_imm_dt          : in  slv(32 downto 0);
      s_work_req_rkey_to_inv     : in  slv(32 downto 0);
      s_work_req_srqn            : in  slv(24 downto 0);
      s_work_req_dqpn            : in  slv(24 downto 0);
      s_work_req_qkey            : in  slv(32 downto 0);
      s_data_stream_tvalid       : in  sl;
      s_data_stream_tdata        : in  slv(255 downto 0);
      s_data_stream_tkeep        : in  slv(31 downto 0);
      s_data_stream_tfirst       : in  sl;
      s_data_stream_tlast        : in  sl;
      m_data_stream_tready       : in  sl;
      m_work_comp_sq_ready       : in  sl;
      s_meta_data_tvalid         : in  sl;
      s_meta_data_tdata          : in  slv(302 downto 0);
      m_meta_data_tready         : in  sl;
      m_dma_read_ready           : in  sl;
      s_dma_read_valid           : in  sl;
      s_dma_read_initiator       : in  slv(3 downto 0);
      s_dma_read_sqpn            : in  slv(23 downto 0);
      s_dma_read_wr_id           : in  slv(63 downto 0);
      s_dma_read_is_resp_err     : in  sl;
      s_dma_read_data_stream     : in  slv(289 downto 0);
      s_work_req_ready           : out sl;
      s_data_stream_tready       : out sl;
      m_data_stream_tvalid       : out sl;
      m_data_stream_tdata        : out slv(255 downto 0);
      m_data_stream_tkeep        : out slv(31 downto 0);
      m_data_stream_tfirst       : out sl;
      m_data_stream_tlast        : out sl;
      m_work_comp_sq_valid       : out sl;
      m_work_comp_sq_id          : out slv(63 downto 0);
      m_work_comp_sq_op_code     : out slv(7 downto 0);
      m_work_comp_sq_flags       : out slv(6 downto 0);
      m_work_comp_sq_status      : out slv(4 downto 0);
      m_work_comp_sq_len         : out slv(31 downto 0);
      m_work_comp_sq_pkey        : out slv(15 downto 0);
      m_work_comp_sq_qpn         : out slv(23 downto 0);
      m_work_comp_sq_imm_dt      : out slv(32 downto 0);
      m_work_comp_sq_rkey_to_inv : out slv(32 downto 0);
      s_meta_data_tready         : out sl;
      m_meta_data_tvalid         : out sl;
      m_meta_data_tdata          : out slv(275 downto 0);
      m_dma_read_valid           : out sl;
      m_dma_read_initiator       : out slv(3 downto 0);
      m_dma_read_sqpn            : out slv(23 downto 0);
      m_dma_read_wr_id           : out slv(63 downto 0);
      m_dma_read_start_addr      : out slv(63 downto 0);
      m_dma_read_len             : out slv(12 downto 0);
      m_dma_read_mr_idx          : out sl;
      s_dma_read_ready           : out sl;
      cnp_received               : out sl);
end mkAxiSTransportLayer;

architecture rtl of mkAxiSTransportLayer is

   signal rawworkreqslvRawbusRawbusDatawWget : slv(600 downto 0);
   signal rawdmareadcltstreamslvRawbusRawbusDatawWget : slv(382 downto 0);
   signal rawmetadatastreamslvRawbusRawbusDatawWget : slv(302 downto 0);
   signal rawrdmadatastreammstRawbusRawbusDatawWget : slv(289 downto 0);
   signal rawrdmadatastreamslvRawbusRawbusDatawWget : slv(289 downto 0);
   signal rawmetadatastreammstRawbusRawbusDatawWget : slv(275 downto 0);
   signal rawworkcompsqmstRawbusRawbusDatawWget : slv(221 downto 0);
   signal rawdmareadcltstreammstRawbusRawbusDatawWget : slv(169 downto 0);
   signal rawdmareadcltstreammstRawbusRawbusDatawWhas : sl;
   signal rawdmareadcltstreammstRawbusRawbusReadywWget : sl;
   signal rawdmareadcltstreamslvRawbusRawbusValidwWget : sl;
   signal rawmetadatastreammstRawbusRawbusDatawWhas : sl;
   signal rawmetadatastreammstRawbusRawbusReadywWget : sl;
   signal rawmetadatastreamslvRawbusRawbusValidwWget : sl;
   signal rawrdmadatastreammstRawbusRawbusDatawWhas : sl;
   signal rawrdmadatastreammstRawbusRawbusReadywWget : sl;
   signal rawrdmadatastreamslvRawbusRawbusValidwWget : sl;
   signal rawworkcompsqmstRawbusRawbusDatawWhas : sl;
   signal rawworkcompsqmstRawbusRawbusReadywWget : sl;
   signal rawworkreqslvRawbusRawbusValidwWget : sl;
   signal rawdmareadcltstreammstRawbusFifoDIn : slv(169 downto 0);
   signal rawdmareadcltstreammstRawbusFifoDOut : slv(169 downto 0);
   signal rawdmareadcltstreammstRawbusFifoClr : sl;
   signal rawdmareadcltstreammstRawbusFifoDeq : sl;
   signal rawdmareadcltstreammstRawbusFifoEmptyN : sl;
   signal rawdmareadcltstreammstRawbusFifoEnq : sl;
   signal rawdmareadcltstreammstRawbusFifoFullN : sl;
   signal rawdmareadcltstreamslvRawbusFifoDIn : slv(382 downto 0);
   signal rawdmareadcltstreamslvRawbusFifoDOut : slv(382 downto 0);
   signal rawdmareadcltstreamslvRawbusFifoClr : sl;
   signal rawdmareadcltstreamslvRawbusFifoDeq : sl;
   signal rawdmareadcltstreamslvRawbusFifoEmptyN : sl;
   signal rawdmareadcltstreamslvRawbusFifoEnq : sl;
   signal rawdmareadcltstreamslvRawbusFifoFullN : sl;
   signal rawmetadatastreammstRawbusFifoDIn : slv(275 downto 0);
   signal rawmetadatastreammstRawbusFifoDOut : slv(275 downto 0);
   signal rawmetadatastreammstRawbusFifoClr : sl;
   signal rawmetadatastreammstRawbusFifoDeq : sl;
   signal rawmetadatastreammstRawbusFifoEmptyN : sl;
   signal rawmetadatastreammstRawbusFifoEnq : sl;
   signal rawmetadatastreammstRawbusFifoFullN : sl;
   signal rawmetadatastreamslvRawbusFifoDIn : slv(302 downto 0);
   signal rawmetadatastreamslvRawbusFifoDOut : slv(302 downto 0);
   signal rawmetadatastreamslvRawbusFifoClr : sl;
   signal rawmetadatastreamslvRawbusFifoDeq : sl;
   signal rawmetadatastreamslvRawbusFifoEmptyN : sl;
   signal rawmetadatastreamslvRawbusFifoEnq : sl;
   signal rawmetadatastreamslvRawbusFifoFullN : sl;
   signal rawrdmadatastreammstRawbusFifoDIn : slv(289 downto 0);
   signal rawrdmadatastreammstRawbusFifoDOut : slv(289 downto 0);
   signal rawrdmadatastreammstRawbusFifoClr : sl;
   signal rawrdmadatastreammstRawbusFifoDeq : sl;
   signal rawrdmadatastreammstRawbusFifoEmptyN : sl;
   signal rawrdmadatastreammstRawbusFifoEnq : sl;
   signal rawrdmadatastreammstRawbusFifoFullN : sl;
   signal rawrdmadatastreamslvRawbusFifoDIn : slv(289 downto 0);
   signal rawrdmadatastreamslvRawbusFifoDOut : slv(289 downto 0);
   signal rawrdmadatastreamslvRawbusFifoClr : sl;
   signal rawrdmadatastreamslvRawbusFifoDeq : sl;
   signal rawrdmadatastreamslvRawbusFifoEmptyN : sl;
   signal rawrdmadatastreamslvRawbusFifoEnq : sl;
   signal rawrdmadatastreamslvRawbusFifoFullN : sl;
   signal rawworkcompsqmstRawbusFifoDIn : slv(221 downto 0);
   signal rawworkcompsqmstRawbusFifoDOut : slv(221 downto 0);
   signal rawworkcompsqmstRawbusFifoClr : sl;
   signal rawworkcompsqmstRawbusFifoDeq : sl;
   signal rawworkcompsqmstRawbusFifoEmptyN : sl;
   signal rawworkcompsqmstRawbusFifoEnq : sl;
   signal rawworkcompsqmstRawbusFifoFullN : sl;
   signal rawworkreqslvRawbusFifoDIn : slv(600 downto 0);
   signal rawworkreqslvRawbusFifoDOut : slv(600 downto 0);
   signal rawworkreqslvRawbusFifoClr : sl;
   signal rawworkreqslvRawbusFifoDeq : sl;
   signal rawworkreqslvRawbusFifoEmptyN : sl;
   signal rawworkreqslvRawbusFifoEnq : sl;
   signal rawworkreqslvRawbusFifoFullN : sl;
   signal transportlayerWorkreqinputPut : slv(600 downto 0);
   signal transportlayerDmareadcltResponsePut : slv(382 downto 0);
   signal transportlayerSrvportmetadataRequestPut : slv(302 downto 0);
   signal transportlayerRdmadatastreaminputPut : slv(289 downto 0);
   signal transportlayerRdmadatastreampipeoutFirst : slv(289 downto 0);
   signal transportlayerSrvportmetadataResponseGet : slv(275 downto 0);
   signal transportlayerWorkcomppipeoutsqFirst : slv(221 downto 0);
   signal transportlayerDmareadcltRequestGet : slv(169 downto 0);
   signal transportlayerEnDmareadcltRequestGet : sl;
   signal transportlayerEnDmareadcltResponsePut : sl;
   signal transportlayerEnRdmadatastreaminputPut : sl;
   signal transportlayerEnRdmadatastreampipeoutDeq : sl;
   signal transportlayerEnSrvportmetadataRequestPut : sl;
   signal transportlayerEnSrvportmetadataResponseGet : sl;
   signal transportlayerEnWorkcomppipeoutsqDeq : sl;
   signal transportlayerEnWorkreqinputPut : sl;
   signal transportlayerRdyDmareadcltRequestGet : sl;
   signal transportlayerRdyDmareadcltResponsePut : sl;
   signal transportlayerRdyRdmadatastreaminputPut : sl;
   signal transportlayerRdyRdmadatastreampipeoutDeq : sl;
   signal transportlayerRdyRdmadatastreampipeoutFirst : sl;
   signal transportlayerRdySrvportmetadataRequestPut : sl;
   signal transportlayerRdySrvportmetadataResponseGet : sl;
   signal transportlayerRdyWorkcomppipeoutsqDeq : sl;
   signal transportlayerRdyWorkcomppipeoutsqFirst : sl;
   signal transportlayerRdyWorkreqinputPut : sl;
   signal transportlayerCnpreceived : sl;
   signal canFireRlRawdmareadcltstreammstRawbusMkconnectiongetput : sl;
   signal canFireRlRawdmareadcltstreammstRawbusRawbusPassready : sl;
   signal canFireRlRawdmareadcltstreammstRawbusRawbusPasswire : sl;
   signal canFireRlRawdmareadcltstreamslvRawbusMkconnectiongetput : sl;
   signal canFireRlRawdmareadcltstreamslvRawbusRawbusPassdata : sl;
   signal canFireRlRawmetadatastreammstRawbusMkconnectiongetput : sl;
   signal canFireRlRawmetadatastreammstRawbusRawbusPassready : sl;
   signal canFireRlRawmetadatastreammstRawbusRawbusPasswire : sl;
   signal canFireRlRawmetadatastreamslvRawbusMkconnectiongetput : sl;
   signal canFireRlRawmetadatastreamslvRawbusRawbusPassdata : sl;
   signal canFireRlRawrdmadatastreammstRawbusMkconnectiongetput : sl;
   signal canFireRlRawrdmadatastreammstRawbusRawbusPassready : sl;
   signal canFireRlRawrdmadatastreammstRawbusRawbusPasswire : sl;
   signal canFireRlRawrdmadatastreamslvRawbusMkconnectiongetput : sl;
   signal canFireRlRawrdmadatastreamslvRawbusRawbusPassdata : sl;
   signal canFireRlRawworkcompsqmstRawbusMkconnectiongetput : sl;
   signal canFireRlRawworkcompsqmstRawbusRawbusPassready : sl;
   signal canFireRlRawworkcompsqmstRawbusRawbusPasswire : sl;
   signal canFireRlRawworkreqslvRawbusMkconnectiongetput : sl;
   signal canFireRlRawworkreqslvRawbusRawbusPassdata : sl;
   signal canFireRawdmareadcltstreaminValiddata : sl;
   signal canFireRawdmareadcltstreamoutReady : sl;
   signal canFireRawmetadatastreaminValiddata : sl;
   signal canFireRawmetadatastreamoutReady : sl;
   signal canFireRawrdmadatastreaminValiddata : sl;
   signal canFireRawrdmadatastreamoutReady : sl;
   signal canFireRawworkcompsqoutReady : sl;
   signal canFireRawworkreqinValiddata : sl;
   signal willFireRlRawdmareadcltstreammstRawbusMkconnectiongetput : sl;
   signal willFireRlRawdmareadcltstreammstRawbusRawbusPassready : sl;
   signal willFireRlRawdmareadcltstreammstRawbusRawbusPasswire : sl;
   signal willFireRlRawdmareadcltstreamslvRawbusMkconnectiongetput : sl;
   signal willFireRlRawdmareadcltstreamslvRawbusRawbusPassdata : sl;
   signal willFireRlRawmetadatastreammstRawbusMkconnectiongetput : sl;
   signal willFireRlRawmetadatastreammstRawbusRawbusPassready : sl;
   signal willFireRlRawmetadatastreammstRawbusRawbusPasswire : sl;
   signal willFireRlRawmetadatastreamslvRawbusMkconnectiongetput : sl;
   signal willFireRlRawmetadatastreamslvRawbusRawbusPassdata : sl;
   signal willFireRlRawrdmadatastreammstRawbusMkconnectiongetput : sl;
   signal willFireRlRawrdmadatastreammstRawbusRawbusPassready : sl;
   signal willFireRlRawrdmadatastreammstRawbusRawbusPasswire : sl;
   signal willFireRlRawrdmadatastreamslvRawbusMkconnectiongetput : sl;
   signal willFireRlRawrdmadatastreamslvRawbusRawbusPassdata : sl;
   signal willFireRlRawworkcompsqmstRawbusMkconnectiongetput : sl;
   signal willFireRlRawworkcompsqmstRawbusRawbusPassready : sl;
   signal willFireRlRawworkcompsqmstRawbusRawbusPasswire : sl;
   signal willFireRlRawworkreqslvRawbusMkconnectiongetput : sl;
   signal willFireRlRawworkreqslvRawbusRawbusPassdata : sl;
   signal willFireRawdmareadcltstreaminValiddata : sl;
   signal willFireRawdmareadcltstreamoutReady : sl;
   signal willFireRawmetadatastreaminValiddata : sl;
   signal willFireRawmetadatastreamoutReady : sl;
   signal willFireRawrdmadatastreaminValiddata : sl;
   signal willFireRawrdmadatastreamoutReady : sl;
   signal willFireRawworkcompsqoutReady : sl;
   signal willFireRawworkreqinValiddata : sl;

   component FIFO2 is
      generic (
         WIDTH_G : positive);
      port (
         RST     : in  sl;
         CLK     : in  sl;
         D_IN    : in  slv(WIDTH_G-1 downto 0);
         ENQ     : in  sl;
         DEQ     : in  sl;
         CLR     : in  sl;
         D_OUT   : out slv(WIDTH_G-1 downto 0);
         FULL_N  : out sl;
         EMPTY_N : out sl);
   end component;

   component mkTransportLayer is
      port (
         CLK                                : in  sl;
         RST_N                              : in  sl;
         dmaReadClt_response_put            : in  slv(382 downto 0);
         rdmaDataStreamInput_put            : in  slv(289 downto 0);
         srvPortMetaData_request_put        : in  slv(302 downto 0);
         workReqInput_put                   : in  slv(600 downto 0);
         EN_workReqInput_put                : in  sl;
         EN_rdmaDataStreamInput_put         : in  sl;
         EN_rdmaDataStreamPipeOut_deq       : in  sl;
         EN_workCompPipeOutSQ_deq           : in  sl;
         EN_srvPortMetaData_request_put     : in  sl;
         EN_srvPortMetaData_response_get    : in  sl;
         EN_dmaReadClt_request_get          : in  sl;
         EN_dmaReadClt_response_put         : in  sl;
         RDY_workReqInput_put               : out sl;
         RDY_rdmaDataStreamInput_put        : out sl;
         rdmaDataStreamPipeOut_first        : out slv(289 downto 0);
         RDY_rdmaDataStreamPipeOut_first    : out sl;
         RDY_rdmaDataStreamPipeOut_deq      : out sl;
         rdmaDataStreamPipeOut_notEmpty     : out sl;
         RDY_rdmaDataStreamPipeOut_notEmpty : out sl;
         workCompPipeOutSQ_first            : out slv(221 downto 0);
         RDY_workCompPipeOutSQ_first        : out sl;
         RDY_workCompPipeOutSQ_deq          : out sl;
         workCompPipeOutSQ_notEmpty         : out sl;
         RDY_workCompPipeOutSQ_notEmpty     : out sl;
         RDY_srvPortMetaData_request_put    : out sl;
         srvPortMetaData_response_get       : out slv(275 downto 0);
         RDY_srvPortMetaData_response_get   : out sl;
         dmaReadClt_request_get             : out slv(169 downto 0);
         RDY_dmaReadClt_request_get         : out sl;
         RDY_dmaReadClt_response_put        : out sl;
         cnpReceived                        : out sl);
   end component;

begin

   rawDmaReadCltStreamMst_rawBus_fifo : FIFO2
      generic map (
         WIDTH_G => 170)
      port map (
         RST     => RST_N,
         CLK     => CLK,
         D_IN    => rawdmareadcltstreammstRawbusFifoDIn,
         ENQ     => rawdmareadcltstreammstRawbusFifoEnq,
         DEQ     => rawdmareadcltstreammstRawbusFifoDeq,
         CLR     => rawdmareadcltstreammstRawbusFifoClr,
         D_OUT   => rawdmareadcltstreammstRawbusFifoDOut,
         FULL_N  => rawdmareadcltstreammstRawbusFifoFullN,
         EMPTY_N => rawdmareadcltstreammstRawbusFifoEmptyN);

   rawDmaReadCltStreamSlv_rawBus_fifo : FIFO2
      generic map (
         WIDTH_G => 383)
      port map (
         RST     => RST_N,
         CLK     => CLK,
         D_IN    => rawdmareadcltstreamslvRawbusFifoDIn,
         ENQ     => rawdmareadcltstreamslvRawbusFifoEnq,
         DEQ     => rawdmareadcltstreamslvRawbusFifoDeq,
         CLR     => rawdmareadcltstreamslvRawbusFifoClr,
         D_OUT   => rawdmareadcltstreamslvRawbusFifoDOut,
         FULL_N  => rawdmareadcltstreamslvRawbusFifoFullN,
         EMPTY_N => rawdmareadcltstreamslvRawbusFifoEmptyN);

   rawMetaDataStreamMst_rawBus_fifo : FIFO2
      generic map (
         WIDTH_G => 276)
      port map (
         RST     => RST_N,
         CLK     => CLK,
         D_IN    => rawmetadatastreammstRawbusFifoDIn,
         ENQ     => rawmetadatastreammstRawbusFifoEnq,
         DEQ     => rawmetadatastreammstRawbusFifoDeq,
         CLR     => rawmetadatastreammstRawbusFifoClr,
         D_OUT   => rawmetadatastreammstRawbusFifoDOut,
         FULL_N  => rawmetadatastreammstRawbusFifoFullN,
         EMPTY_N => rawmetadatastreammstRawbusFifoEmptyN);

   rawMetaDataStreamSlv_rawBus_fifo : FIFO2
      generic map (
         WIDTH_G => 303)
      port map (
         RST     => RST_N,
         CLK     => CLK,
         D_IN    => rawmetadatastreamslvRawbusFifoDIn,
         ENQ     => rawmetadatastreamslvRawbusFifoEnq,
         DEQ     => rawmetadatastreamslvRawbusFifoDeq,
         CLR     => rawmetadatastreamslvRawbusFifoClr,
         D_OUT   => rawmetadatastreamslvRawbusFifoDOut,
         FULL_N  => rawmetadatastreamslvRawbusFifoFullN,
         EMPTY_N => rawmetadatastreamslvRawbusFifoEmptyN);

   rawRdmaDataStreamMst_rawBus_fifo : FIFO2
      generic map (
         WIDTH_G => 290)
      port map (
         RST     => RST_N,
         CLK     => CLK,
         D_IN    => rawrdmadatastreammstRawbusFifoDIn,
         ENQ     => rawrdmadatastreammstRawbusFifoEnq,
         DEQ     => rawrdmadatastreammstRawbusFifoDeq,
         CLR     => rawrdmadatastreammstRawbusFifoClr,
         D_OUT   => rawrdmadatastreammstRawbusFifoDOut,
         FULL_N  => rawrdmadatastreammstRawbusFifoFullN,
         EMPTY_N => rawrdmadatastreammstRawbusFifoEmptyN);

   rawRdmaDataStreamSlv_rawBus_fifo : FIFO2
      generic map (
         WIDTH_G => 290)
      port map (
         RST     => RST_N,
         CLK     => CLK,
         D_IN    => rawrdmadatastreamslvRawbusFifoDIn,
         ENQ     => rawrdmadatastreamslvRawbusFifoEnq,
         DEQ     => rawrdmadatastreamslvRawbusFifoDeq,
         CLR     => rawrdmadatastreamslvRawbusFifoClr,
         D_OUT   => rawrdmadatastreamslvRawbusFifoDOut,
         FULL_N  => rawrdmadatastreamslvRawbusFifoFullN,
         EMPTY_N => rawrdmadatastreamslvRawbusFifoEmptyN);

   rawWorkCompSQMst_rawBus_fifo : FIFO2
      generic map (
         WIDTH_G => 222)
      port map (
         RST     => RST_N,
         CLK     => CLK,
         D_IN    => rawworkcompsqmstRawbusFifoDIn,
         ENQ     => rawworkcompsqmstRawbusFifoEnq,
         DEQ     => rawworkcompsqmstRawbusFifoDeq,
         CLR     => rawworkcompsqmstRawbusFifoClr,
         D_OUT   => rawworkcompsqmstRawbusFifoDOut,
         FULL_N  => rawworkcompsqmstRawbusFifoFullN,
         EMPTY_N => rawworkcompsqmstRawbusFifoEmptyN);

   rawWorkReqSlv_rawBus_fifo : FIFO2
      generic map (
         WIDTH_G => 601)
      port map (
         RST     => RST_N,
         CLK     => CLK,
         D_IN    => rawworkreqslvRawbusFifoDIn,
         ENQ     => rawworkreqslvRawbusFifoEnq,
         DEQ     => rawworkreqslvRawbusFifoDeq,
         CLR     => rawworkreqslvRawbusFifoClr,
         D_OUT   => rawworkreqslvRawbusFifoDOut,
         FULL_N  => rawworkreqslvRawbusFifoFullN,
         EMPTY_N => rawworkreqslvRawbusFifoEmptyN);

   transportLayer : mkTransportLayer
      port map (
         CLK                                => CLK,
         RST_N                              => RST_N,
         dmaReadClt_response_put            => transportlayerDmareadcltResponsePut,
         rdmaDataStreamInput_put            => transportlayerRdmadatastreaminputPut,
         srvPortMetaData_request_put        => transportlayerSrvportmetadataRequestPut,
         workReqInput_put                   => transportlayerWorkreqinputPut,
         EN_workReqInput_put                => transportlayerEnWorkreqinputPut,
         EN_rdmaDataStreamInput_put         => transportlayerEnRdmadatastreaminputPut,
         EN_rdmaDataStreamPipeOut_deq       => transportlayerEnRdmadatastreampipeoutDeq,
         EN_workCompPipeOutSQ_deq           => transportlayerEnWorkcomppipeoutsqDeq,
         EN_srvPortMetaData_request_put     => transportlayerEnSrvportmetadataRequestPut,
         EN_srvPortMetaData_response_get    => transportlayerEnSrvportmetadataResponseGet,
         EN_dmaReadClt_request_get          => transportlayerEnDmareadcltRequestGet,
         EN_dmaReadClt_response_put         => transportlayerEnDmareadcltResponsePut,
         RDY_workReqInput_put               => transportlayerRdyWorkreqinputPut,
         RDY_rdmaDataStreamInput_put        => transportlayerRdyRdmadatastreaminputPut,
         rdmaDataStreamPipeOut_first        => transportlayerRdmadatastreampipeoutFirst,
         RDY_rdmaDataStreamPipeOut_first    => transportlayerRdyRdmadatastreampipeoutFirst,
         RDY_rdmaDataStreamPipeOut_deq      => transportlayerRdyRdmadatastreampipeoutDeq,
         rdmaDataStreamPipeOut_notEmpty     => open,
         RDY_rdmaDataStreamPipeOut_notEmpty => open,
         workCompPipeOutSQ_first            => transportlayerWorkcomppipeoutsqFirst,
         RDY_workCompPipeOutSQ_first        => transportlayerRdyWorkcomppipeoutsqFirst,
         RDY_workCompPipeOutSQ_deq          => transportlayerRdyWorkcomppipeoutsqDeq,
         workCompPipeOutSQ_notEmpty         => open,
         RDY_workCompPipeOutSQ_notEmpty     => open,
         RDY_srvPortMetaData_request_put    => transportlayerRdySrvportmetadataRequestPut,
         srvPortMetaData_response_get       => transportlayerSrvportmetadataResponseGet,
         RDY_srvPortMetaData_response_get   => transportlayerRdySrvportmetadataResponseGet,
         dmaReadClt_request_get             => transportlayerDmareadcltRequestGet,
         RDY_dmaReadClt_request_get         => transportlayerRdyDmareadcltRequestGet,
         RDY_dmaReadClt_response_put        => transportlayerRdyDmareadcltResponsePut,
         cnpReceived                        => transportlayerCnpreceived);

   canFireRawworkreqinValiddata <= '1';
   willFireRawworkreqinValiddata <= '1';
   s_work_req_ready <= rawworkreqslvRawbusFifoFullN;
   canFireRawrdmadatastreaminValiddata <= '1';
   willFireRawrdmadatastreaminValiddata <= '1';
   s_data_stream_tready <= rawrdmadatastreamslvRawbusFifoFullN;
   m_data_stream_tvalid <= rawrdmadatastreammstRawbusFifoEmptyN;
   m_data_stream_tdata <= resize(rawrdmadatastreammstRawbusFifoDOut(289 downto 34), (255) - (0) + 1);
   m_data_stream_tkeep <= resize(rawrdmadatastreammstRawbusFifoDOut(33 downto 2), (31) - (0) + 1);
   m_data_stream_tfirst <= rawrdmadatastreammstRawbusFifoDOut(1);
   m_data_stream_tlast <= rawrdmadatastreammstRawbusFifoDOut(0);
   canFireRawrdmadatastreamoutReady <= '1';
   willFireRawrdmadatastreamoutReady <= '1';
   m_work_comp_sq_valid <= rawworkcompsqmstRawbusFifoEmptyN;
   m_work_comp_sq_id <= resize(rawworkcompsqmstRawbusFifoDOut(221 downto 158), (63) - (0) + 1);
   m_work_comp_sq_op_code <= resize(rawworkcompsqmstRawbusFifoDOut(157 downto 150), (7) - (0) + 1);
   m_work_comp_sq_flags <= resize(rawworkcompsqmstRawbusFifoDOut(149 downto 143), (6) - (0) + 1);
   m_work_comp_sq_status <= resize(rawworkcompsqmstRawbusFifoDOut(142 downto 138), (4) - (0) + 1);
   m_work_comp_sq_len <= resize(rawworkcompsqmstRawbusFifoDOut(137 downto 106), (31) - (0) + 1);
   m_work_comp_sq_pkey <= resize(rawworkcompsqmstRawbusFifoDOut(105 downto 90), (15) - (0) + 1);
   m_work_comp_sq_qpn <= resize(rawworkcompsqmstRawbusFifoDOut(89 downto 66), (23) - (0) + 1);
   m_work_comp_sq_imm_dt <= resize(rawworkcompsqmstRawbusFifoDOut(65 downto 33), (32) - (0) + 1);
   m_work_comp_sq_rkey_to_inv <= resize(rawworkcompsqmstRawbusFifoDOut(32 downto 0), (32) - (0) + 1);
   canFireRawworkcompsqoutReady <= '1';
   willFireRawworkcompsqoutReady <= '1';
   canFireRawmetadatastreaminValiddata <= '1';
   willFireRawmetadatastreaminValiddata <= '1';
   s_meta_data_tready <= rawmetadatastreamslvRawbusFifoFullN;
   m_meta_data_tvalid <= rawmetadatastreammstRawbusFifoEmptyN;
   m_meta_data_tdata <= rawmetadatastreammstRawbusFifoDOut;
   canFireRawmetadatastreamoutReady <= '1';
   willFireRawmetadatastreamoutReady <= '1';
   m_dma_read_valid <= rawdmareadcltstreammstRawbusFifoEmptyN;
   m_dma_read_initiator <= resize(rawdmareadcltstreammstRawbusFifoDOut(169 downto 166), (3) - (0) + 1);
   m_dma_read_sqpn <= resize(rawdmareadcltstreammstRawbusFifoDOut(165 downto 142), (23) - (0) + 1);
   m_dma_read_wr_id <= resize(rawdmareadcltstreammstRawbusFifoDOut(141 downto 78), (63) - (0) + 1);
   m_dma_read_start_addr <= resize(rawdmareadcltstreammstRawbusFifoDOut(77 downto 14), (63) - (0) + 1);
   m_dma_read_len <= resize(rawdmareadcltstreammstRawbusFifoDOut(13 downto 1), (12) - (0) + 1);
   m_dma_read_mr_idx <= rawdmareadcltstreammstRawbusFifoDOut(0);
   canFireRawdmareadcltstreamoutReady <= '1';
   willFireRawdmareadcltstreamoutReady <= '1';
   canFireRawdmareadcltstreaminValiddata <= '1';
   willFireRawdmareadcltstreaminValiddata <= '1';
   s_dma_read_ready <= rawdmareadcltstreamslvRawbusFifoFullN;
   cnp_received <= transportlayerCnpreceived;
   canFireRlRawworkreqslvRawbusMkconnectiongetput <= (transportlayerRdyWorkreqinputPut and rawworkreqslvRawbusFifoEmptyN);
   willFireRlRawworkreqslvRawbusMkconnectiongetput <= canFireRlRawworkreqslvRawbusMkconnectiongetput;
   canFireRlRawworkreqslvRawbusRawbusPassdata <= (rawworkreqslvRawbusFifoFullN and s_work_req_valid);
   willFireRlRawworkreqslvRawbusRawbusPassdata <= canFireRlRawworkreqslvRawbusRawbusPassdata;
   canFireRlRawrdmadatastreamslvRawbusMkconnectiongetput <= (transportlayerRdyRdmadatastreaminputPut and rawrdmadatastreamslvRawbusFifoEmptyN);
   willFireRlRawrdmadatastreamslvRawbusMkconnectiongetput <= canFireRlRawrdmadatastreamslvRawbusMkconnectiongetput;
   canFireRlRawrdmadatastreamslvRawbusRawbusPassdata <= (rawrdmadatastreamslvRawbusFifoFullN and s_data_stream_tvalid);
   willFireRlRawrdmadatastreamslvRawbusRawbusPassdata <= canFireRlRawrdmadatastreamslvRawbusRawbusPassdata;
   canFireRlRawrdmadatastreammstRawbusRawbusPasswire <= rawrdmadatastreammstRawbusFifoEmptyN;
   willFireRlRawrdmadatastreammstRawbusRawbusPasswire <= rawrdmadatastreammstRawbusFifoEmptyN;
   canFireRlRawrdmadatastreammstRawbusRawbusPassready <= (rawrdmadatastreammstRawbusFifoEmptyN and m_data_stream_tready);
   willFireRlRawrdmadatastreammstRawbusRawbusPassready <= canFireRlRawrdmadatastreammstRawbusRawbusPassready;
   canFireRlRawrdmadatastreammstRawbusMkconnectiongetput <= ((transportlayerRdyRdmadatastreampipeoutDeq and transportlayerRdyRdmadatastreampipeoutFirst) and rawrdmadatastreammstRawbusFifoFullN);
   willFireRlRawrdmadatastreammstRawbusMkconnectiongetput <= canFireRlRawrdmadatastreammstRawbusMkconnectiongetput;
   canFireRlRawworkcompsqmstRawbusRawbusPasswire <= rawworkcompsqmstRawbusFifoEmptyN;
   willFireRlRawworkcompsqmstRawbusRawbusPasswire <= rawworkcompsqmstRawbusFifoEmptyN;
   canFireRlRawworkcompsqmstRawbusRawbusPassready <= (rawworkcompsqmstRawbusFifoEmptyN and m_work_comp_sq_ready);
   willFireRlRawworkcompsqmstRawbusRawbusPassready <= canFireRlRawworkcompsqmstRawbusRawbusPassready;
   canFireRlRawworkcompsqmstRawbusMkconnectiongetput <= ((transportlayerRdyWorkcomppipeoutsqDeq and transportlayerRdyWorkcomppipeoutsqFirst) and rawworkcompsqmstRawbusFifoFullN);
   willFireRlRawworkcompsqmstRawbusMkconnectiongetput <= canFireRlRawworkcompsqmstRawbusMkconnectiongetput;
   canFireRlRawmetadatastreammstRawbusRawbusPasswire <= rawmetadatastreammstRawbusFifoEmptyN;
   willFireRlRawmetadatastreammstRawbusRawbusPasswire <= rawmetadatastreammstRawbusFifoEmptyN;
   canFireRlRawmetadatastreammstRawbusRawbusPassready <= (rawmetadatastreammstRawbusFifoEmptyN and m_meta_data_tready);
   willFireRlRawmetadatastreammstRawbusRawbusPassready <= canFireRlRawmetadatastreammstRawbusRawbusPassready;
   canFireRlRawmetadatastreammstRawbusMkconnectiongetput <= (transportlayerRdySrvportmetadataResponseGet and rawmetadatastreammstRawbusFifoFullN);
   willFireRlRawmetadatastreammstRawbusMkconnectiongetput <= canFireRlRawmetadatastreammstRawbusMkconnectiongetput;
   canFireRlRawmetadatastreamslvRawbusMkconnectiongetput <= (transportlayerRdySrvportmetadataRequestPut and rawmetadatastreamslvRawbusFifoEmptyN);
   willFireRlRawmetadatastreamslvRawbusMkconnectiongetput <= canFireRlRawmetadatastreamslvRawbusMkconnectiongetput;
   canFireRlRawmetadatastreamslvRawbusRawbusPassdata <= (rawmetadatastreamslvRawbusFifoFullN and s_meta_data_tvalid);
   willFireRlRawmetadatastreamslvRawbusRawbusPassdata <= canFireRlRawmetadatastreamslvRawbusRawbusPassdata;
   canFireRlRawdmareadcltstreammstRawbusRawbusPasswire <= rawdmareadcltstreammstRawbusFifoEmptyN;
   willFireRlRawdmareadcltstreammstRawbusRawbusPasswire <= rawdmareadcltstreammstRawbusFifoEmptyN;
   canFireRlRawdmareadcltstreammstRawbusRawbusPassready <= (rawdmareadcltstreammstRawbusFifoEmptyN and m_dma_read_ready);
   willFireRlRawdmareadcltstreammstRawbusRawbusPassready <= canFireRlRawdmareadcltstreammstRawbusRawbusPassready;
   canFireRlRawdmareadcltstreammstRawbusMkconnectiongetput <= (transportlayerRdyDmareadcltRequestGet and rawdmareadcltstreammstRawbusFifoFullN);
   willFireRlRawdmareadcltstreammstRawbusMkconnectiongetput <= canFireRlRawdmareadcltstreammstRawbusMkconnectiongetput;
   canFireRlRawdmareadcltstreamslvRawbusMkconnectiongetput <= (transportlayerRdyDmareadcltResponsePut and rawdmareadcltstreamslvRawbusFifoEmptyN);
   willFireRlRawdmareadcltstreamslvRawbusMkconnectiongetput <= canFireRlRawdmareadcltstreamslvRawbusMkconnectiongetput;
   canFireRlRawdmareadcltstreamslvRawbusRawbusPassdata <= (rawdmareadcltstreamslvRawbusFifoFullN and s_dma_read_valid);
   willFireRlRawdmareadcltstreamslvRawbusRawbusPassdata <= canFireRlRawdmareadcltstreamslvRawbusRawbusPassdata;
   rawrdmadatastreammstRawbusRawbusDatawWget <= rawrdmadatastreammstRawbusFifoDOut;
   rawrdmadatastreammstRawbusRawbusDatawWhas <= rawrdmadatastreammstRawbusFifoEmptyN;
   rawworkcompsqmstRawbusRawbusDatawWget <= rawworkcompsqmstRawbusFifoDOut;
   rawworkcompsqmstRawbusRawbusDatawWhas <= rawworkcompsqmstRawbusFifoEmptyN;
   rawmetadatastreammstRawbusRawbusDatawWget <= rawmetadatastreammstRawbusFifoDOut;
   rawmetadatastreammstRawbusRawbusDatawWhas <= rawmetadatastreammstRawbusFifoEmptyN;
   rawdmareadcltstreammstRawbusRawbusDatawWget <= rawdmareadcltstreammstRawbusFifoDOut;
   rawdmareadcltstreammstRawbusRawbusDatawWhas <= rawdmareadcltstreammstRawbusFifoEmptyN;
   rawworkreqslvRawbusRawbusValidwWget <= s_work_req_valid;
   rawworkreqslvRawbusRawbusDatawWget <= resize((s_work_req_id & s_work_req_op_code & s_work_req_flags & s_work_req_raddr & s_work_req_rkey & s_work_req_len & s_work_req_laddr & s_work_req_lkey & s_work_req_sqpn & s_work_req_solicited & s_work_req_comp & s_work_req_swap & s_work_req_imm_dt & s_work_req_rkey_to_inv & s_work_req_srqn & s_work_req_dqpn & s_work_req_qkey), (600) - (0) + 1);
   rawrdmadatastreamslvRawbusRawbusValidwWget <= s_data_stream_tvalid;
   rawrdmadatastreamslvRawbusRawbusDatawWget <= resize((s_data_stream_tdata & s_data_stream_tkeep & s_data_stream_tfirst & s_data_stream_tlast), (289) - (0) + 1);
   rawrdmadatastreammstRawbusRawbusReadywWget <= m_data_stream_tready;
   rawworkcompsqmstRawbusRawbusReadywWget <= m_work_comp_sq_ready;
   rawmetadatastreammstRawbusRawbusReadywWget <= m_meta_data_tready;
   rawmetadatastreamslvRawbusRawbusValidwWget <= s_meta_data_tvalid;
   rawmetadatastreamslvRawbusRawbusDatawWget <= s_meta_data_tdata;
   rawdmareadcltstreammstRawbusRawbusReadywWget <= m_dma_read_ready;
   rawdmareadcltstreamslvRawbusRawbusValidwWget <= s_dma_read_valid;
   rawdmareadcltstreamslvRawbusRawbusDatawWget <= resize((s_dma_read_initiator & s_dma_read_sqpn & s_dma_read_wr_id & s_dma_read_is_resp_err & s_dma_read_data_stream), (382) - (0) + 1);
   rawdmareadcltstreammstRawbusFifoDIn <= transportlayerDmareadcltRequestGet;
   rawdmareadcltstreammstRawbusFifoEnq <= canFireRlRawdmareadcltstreammstRawbusMkconnectiongetput;
   rawdmareadcltstreammstRawbusFifoDeq <= canFireRlRawdmareadcltstreammstRawbusRawbusPassready;
   rawdmareadcltstreammstRawbusFifoClr <= '0';
   rawdmareadcltstreamslvRawbusFifoDIn <= rawdmareadcltstreamslvRawbusRawbusDatawWget;
   rawdmareadcltstreamslvRawbusFifoEnq <= canFireRlRawdmareadcltstreamslvRawbusRawbusPassdata;
   rawdmareadcltstreamslvRawbusFifoDeq <= canFireRlRawdmareadcltstreamslvRawbusMkconnectiongetput;
   rawdmareadcltstreamslvRawbusFifoClr <= '0';
   rawmetadatastreammstRawbusFifoEnq <= canFireRlRawmetadatastreammstRawbusMkconnectiongetput;
   rawmetadatastreammstRawbusFifoDeq <= canFireRlRawmetadatastreammstRawbusRawbusPassready;
   rawmetadatastreammstRawbusFifoClr <= '0';
   rawmetadatastreamslvRawbusFifoDIn <= s_meta_data_tdata;
   rawmetadatastreamslvRawbusFifoEnq <= canFireRlRawmetadatastreamslvRawbusRawbusPassdata;
   rawmetadatastreamslvRawbusFifoDeq <= canFireRlRawmetadatastreamslvRawbusMkconnectiongetput;
   rawmetadatastreamslvRawbusFifoClr <= '0';
   rawrdmadatastreammstRawbusFifoDIn <= transportlayerRdmadatastreampipeoutFirst;
   rawrdmadatastreammstRawbusFifoEnq <= canFireRlRawrdmadatastreammstRawbusMkconnectiongetput;
   rawrdmadatastreammstRawbusFifoDeq <= canFireRlRawrdmadatastreammstRawbusRawbusPassready;
   rawrdmadatastreammstRawbusFifoClr <= '0';
   rawrdmadatastreamslvRawbusFifoDIn <= rawrdmadatastreamslvRawbusRawbusDatawWget;
   rawrdmadatastreamslvRawbusFifoEnq <= canFireRlRawrdmadatastreamslvRawbusRawbusPassdata;
   rawrdmadatastreamslvRawbusFifoDeq <= canFireRlRawrdmadatastreamslvRawbusMkconnectiongetput;
   rawrdmadatastreamslvRawbusFifoClr <= '0';
   rawworkcompsqmstRawbusFifoDIn <= transportlayerWorkcomppipeoutsqFirst;
   rawworkcompsqmstRawbusFifoEnq <= canFireRlRawworkcompsqmstRawbusMkconnectiongetput;
   rawworkcompsqmstRawbusFifoDeq <= canFireRlRawworkcompsqmstRawbusRawbusPassready;
   rawworkcompsqmstRawbusFifoClr <= '0';
   rawworkreqslvRawbusFifoDIn <= rawworkreqslvRawbusRawbusDatawWget;
   rawworkreqslvRawbusFifoEnq <= canFireRlRawworkreqslvRawbusRawbusPassdata;
   rawworkreqslvRawbusFifoDeq <= canFireRlRawworkreqslvRawbusMkconnectiongetput;
   rawworkreqslvRawbusFifoClr <= '0';
   transportlayerDmareadcltResponsePut <= rawdmareadcltstreamslvRawbusFifoDOut;
   transportlayerRdmadatastreaminputPut <= rawrdmadatastreamslvRawbusFifoDOut;
   transportlayerSrvportmetadataRequestPut <= rawmetadatastreamslvRawbusFifoDOut;
   transportlayerWorkreqinputPut <= rawworkreqslvRawbusFifoDOut;
   transportlayerEnWorkreqinputPut <= canFireRlRawworkreqslvRawbusMkconnectiongetput;
   transportlayerEnRdmadatastreaminputPut <= canFireRlRawrdmadatastreamslvRawbusMkconnectiongetput;
   transportlayerEnRdmadatastreampipeoutDeq <= canFireRlRawrdmadatastreammstRawbusMkconnectiongetput;
   transportlayerEnWorkcomppipeoutsqDeq <= canFireRlRawworkcompsqmstRawbusMkconnectiongetput;
   transportlayerEnSrvportmetadataRequestPut <= canFireRlRawmetadatastreamslvRawbusMkconnectiongetput;
   transportlayerEnSrvportmetadataResponseGet <= canFireRlRawmetadatastreammstRawbusMkconnectiongetput;
   transportlayerEnDmareadcltRequestGet <= canFireRlRawdmareadcltstreammstRawbusMkconnectiongetput;
   transportlayerEnDmareadcltResponsePut <= canFireRlRawdmareadcltstreamslvRawbusMkconnectiongetput;

   process (transportlayerSrvportmetadataResponseGet) is
   begin
      case transportlayerSrvportmetadataResponseGet(275 downto 274) is
         when "00" | "01" | "10" =>
            rawmetadatastreammstRawbusFifoDIn <= transportlayerSrvportmetadataResponseGet;
         when "11" =>
            rawmetadatastreammstRawbusFifoDIn <= resize("101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010101010", (275) - (0) + 1);
         when others =>
            null;
      end case;
   end process;

end rtl;
